# Generated by Django 4.2.7 on 2023-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_usernotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserNotePictures/')),
            ],
            options={
                'verbose_name': 'User Note Images',
            },
        ),
        migrations.RemoveField(
            model_name='usernotes',
            name='image',
        ),
        migrations.AddField(
            model_name='usernotes',
            name='image',
            field=models.ManyToManyField(to='UserData.imagefile'),
        ),
    ]
