# Generated by Django 4.2.7 on 2023-11-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_imagefile_remove_usernotes_image_usernotes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='image',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='user_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserData.usernotes'),
        ),
    ]
