# Generated by Django 4.2.7 on 2023-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_remove_usernotes_image_imagefile_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='description',
            field=models.TextField(),
        ),
    ]
