# Generated by Django 4.2.7 on 2023-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_alter_usernotes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
