# Generated by Django 4.2.7 on 2023-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_usernotes_tags_alter_usernotes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='tags',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
