# Generated by Django 4.2.7 on 2023-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0007_alter_usernotes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
