# Generated by Django 4.2.7 on 2023-12-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_alter_usernotes_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefile',
            options={'verbose_name': 'User Note Image'},
        ),
        migrations.AlterModelOptions(
            name='usernotes',
            options={'verbose_name': 'User Note'},
        ),
    ]
